[package]
name = "$PROJECT_NAME$"
version = "0.1.0"
edition = "2021"

[dependencies]
pico-sdk = { git = "https://github.com/brevis-network/brevis-vm.git", branch = "cli" }
serde = { version = "1.0.205", features = ["derive"] }