[package]
name = "prover"
version = "0.1.0"
edition = "2024"

[dependencies]
pico-sdk = { path = "../../../brevis-vm/pico/sdk" }
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
alloy-sol-types = { workspace = true }
fibonacci-lib ={ path = "../lib"}